// This file was generated by Mendix Studio Pro.
//
// WARNING: Code you write here will be lost the next time you deploy the project.

package myfirstmodule.proxies.microflows;

import java.util.HashMap;
import java.util.Map;
import com.mendix.core.Core;
import com.mendix.systemwideinterfaces.core.IContext;

public class Microflows
{
	/**
	 * @deprecated
	 * The default constructor of the Microflows class should not be used.
	 * Use the static microflow invocation methods instead.
	 */
	@java.lang.Deprecated(since = "9.12", forRemoval = true)
	public Microflows() {}

	// These are the microflows for the MyFirstModule module
	public static void generate_person_PDF(IContext context, myfirstmodule.proxies.persoon _persoon)
	{
		Map<java.lang.String, Object> params = new HashMap<>();
		params.put("persoon", _persoon == null ? null : _persoon.getMendixObject());
		Core.microflowCall("MyFirstModule.Generate_person_PDF").withParams(params).execute(context);
	}
	public static void generatePDF(IContext context, myfirstmodule.proxies.invoice _invoice)
	{
		Map<java.lang.String, Object> params = new HashMap<>();
		params.put("invoice", _invoice == null ? null : _invoice.getMendixObject());
		Core.microflowCall("MyFirstModule.GeneratePDF").withParams(params).execute(context);
	}
	public static void show_person_pdf(IContext context, myfirstmodule.proxies.persoon _person)
	{
		Map<java.lang.String, Object> params = new HashMap<>();
		params.put("person", _person == null ? null : _person.getMendixObject());
		Core.microflowCall("MyFirstModule.show_person_pdf").withParams(params).execute(context);
	}
	public static void showPage(IContext context, myfirstmodule.proxies.invoice _invoice)
	{
		Map<java.lang.String, Object> params = new HashMap<>();
		params.put("invoice", _invoice == null ? null : _invoice.getMendixObject());
		Core.microflowCall("MyFirstModule.ShowPage").withParams(params).execute(context);
	}
}
