// This file was generated by Mendix Studio Pro.
//
// WARNING: Code you write here will be lost the next time you deploy the project.

package myfirstmodule.proxies;

public class persoon
{
	private final com.mendix.systemwideinterfaces.core.IMendixObject persoonMendixObject;

	private final com.mendix.systemwideinterfaces.core.IContext context;

	/**
	 * Internal name of this entity
	 */
	public static final java.lang.String entityName = "MyFirstModule.persoon";

	/**
	 * Enum describing members of this entity
	 */
	public enum MemberNames
	{
		voornaam("voornaam"),
		achternaam("achternaam"),
		geboortedatum("geboortedatum"),
		hobby("hobby"),
		gender("gender");

		private final java.lang.String metaName;

		MemberNames(java.lang.String s)
		{
			metaName = s;
		}

		@java.lang.Override
		public java.lang.String toString()
		{
			return metaName;
		}
	}

	public persoon(com.mendix.systemwideinterfaces.core.IContext context)
	{
		this(context, com.mendix.core.Core.instantiate(context, entityName));
	}

	protected persoon(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixObject persoonMendixObject)
	{
		if (persoonMendixObject == null) {
			throw new java.lang.IllegalArgumentException("The given object cannot be null.");
		}
		if (!com.mendix.core.Core.isSubClassOf(entityName, persoonMendixObject.getType())) {
			throw new java.lang.IllegalArgumentException(String.format("The given object is not a %s", entityName));
		}	

		this.persoonMendixObject = persoonMendixObject;
		this.context = context;
	}

	/**
	 * @deprecated Use 'persoon.load(IContext, IMendixIdentifier)' instead.
	 */
	@java.lang.Deprecated
	public static myfirstmodule.proxies.persoon initialize(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixIdentifier mendixIdentifier) throws com.mendix.core.CoreException
	{
		return myfirstmodule.proxies.persoon.load(context, mendixIdentifier);
	}

	/**
	 * Initialize a proxy using context (recommended). This context will be used for security checking when the get- and set-methods without context parameters are called.
	 * The get- and set-methods with context parameter should be used when for instance sudo access is necessary (IContext.createSudoClone() can be used to obtain sudo access).
	 * @param context The context to be used
	 * @param mendixObject The Mendix object for the new instance
	 * @return a new instance of this proxy class
	 */
	public static myfirstmodule.proxies.persoon initialize(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixObject mendixObject)
	{
		return new myfirstmodule.proxies.persoon(context, mendixObject);
	}

	public static myfirstmodule.proxies.persoon load(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixIdentifier mendixIdentifier) throws com.mendix.core.CoreException
	{
		com.mendix.systemwideinterfaces.core.IMendixObject mendixObject = com.mendix.core.Core.retrieveId(context, mendixIdentifier);
		return myfirstmodule.proxies.persoon.initialize(context, mendixObject);
	}

	public static java.util.List<myfirstmodule.proxies.persoon> load(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String xpathConstraint) throws com.mendix.core.CoreException
	{
		return com.mendix.core.Core.createXPathQuery(String.format("//%1$s%2$s", entityName, xpathConstraint))
			.execute(context)
			.stream()
			.map(obj -> myfirstmodule.proxies.persoon.initialize(context, obj))
			.collect(java.util.stream.Collectors.toList());
	}

	/**
	 * Commit the changes made on this proxy object.
	 * @throws com.mendix.core.CoreException
	 */
	public final void commit() throws com.mendix.core.CoreException
	{
		com.mendix.core.Core.commit(context, getMendixObject());
	}

	/**
	 * Commit the changes made on this proxy object using the specified context.
	 * @throws com.mendix.core.CoreException
	 */
	public final void commit(com.mendix.systemwideinterfaces.core.IContext context) throws com.mendix.core.CoreException
	{
		com.mendix.core.Core.commit(context, getMendixObject());
	}

	/**
	 * Delete the object.
	 */
	public final void delete()
	{
		com.mendix.core.Core.delete(context, getMendixObject());
	}

	/**
	 * Delete the object using the specified context.
	 */
	public final void delete(com.mendix.systemwideinterfaces.core.IContext context)
	{
		com.mendix.core.Core.delete(context, getMendixObject());
	}
	/**
	 * @return value of voornaam
	 */
	public final java.lang.String getvoornaam()
	{
		return getvoornaam(getContext());
	}

	/**
	 * @param context
	 * @return value of voornaam
	 */
	public final java.lang.String getvoornaam(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.String) getMendixObject().getValue(context, MemberNames.voornaam.toString());
	}

	/**
	 * Set value of voornaam
	 * @param voornaam
	 */
	public final void setvoornaam(java.lang.String voornaam)
	{
		setvoornaam(getContext(), voornaam);
	}

	/**
	 * Set value of voornaam
	 * @param context
	 * @param voornaam
	 */
	public final void setvoornaam(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String voornaam)
	{
		getMendixObject().setValue(context, MemberNames.voornaam.toString(), voornaam);
	}

	/**
	 * @return value of achternaam
	 */
	public final java.lang.String getachternaam()
	{
		return getachternaam(getContext());
	}

	/**
	 * @param context
	 * @return value of achternaam
	 */
	public final java.lang.String getachternaam(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.String) getMendixObject().getValue(context, MemberNames.achternaam.toString());
	}

	/**
	 * Set value of achternaam
	 * @param achternaam
	 */
	public final void setachternaam(java.lang.String achternaam)
	{
		setachternaam(getContext(), achternaam);
	}

	/**
	 * Set value of achternaam
	 * @param context
	 * @param achternaam
	 */
	public final void setachternaam(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String achternaam)
	{
		getMendixObject().setValue(context, MemberNames.achternaam.toString(), achternaam);
	}

	/**
	 * @return value of geboortedatum
	 */
	public final java.util.Date getgeboortedatum()
	{
		return getgeboortedatum(getContext());
	}

	/**
	 * @param context
	 * @return value of geboortedatum
	 */
	public final java.util.Date getgeboortedatum(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.util.Date) getMendixObject().getValue(context, MemberNames.geboortedatum.toString());
	}

	/**
	 * Set value of geboortedatum
	 * @param geboortedatum
	 */
	public final void setgeboortedatum(java.util.Date geboortedatum)
	{
		setgeboortedatum(getContext(), geboortedatum);
	}

	/**
	 * Set value of geboortedatum
	 * @param context
	 * @param geboortedatum
	 */
	public final void setgeboortedatum(com.mendix.systemwideinterfaces.core.IContext context, java.util.Date geboortedatum)
	{
		getMendixObject().setValue(context, MemberNames.geboortedatum.toString(), geboortedatum);
	}

	/**
	 * @return value of hobby
	 */
	public final java.lang.String gethobby()
	{
		return gethobby(getContext());
	}

	/**
	 * @param context
	 * @return value of hobby
	 */
	public final java.lang.String gethobby(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.String) getMendixObject().getValue(context, MemberNames.hobby.toString());
	}

	/**
	 * Set value of hobby
	 * @param hobby
	 */
	public final void sethobby(java.lang.String hobby)
	{
		sethobby(getContext(), hobby);
	}

	/**
	 * Set value of hobby
	 * @param context
	 * @param hobby
	 */
	public final void sethobby(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String hobby)
	{
		getMendixObject().setValue(context, MemberNames.hobby.toString(), hobby);
	}

	/**
	 * @return value of gender
	 */
	public final java.lang.String getgender()
	{
		return getgender(getContext());
	}

	/**
	 * @param context
	 * @return value of gender
	 */
	public final java.lang.String getgender(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.String) getMendixObject().getValue(context, MemberNames.gender.toString());
	}

	/**
	 * Set value of gender
	 * @param gender
	 */
	public final void setgender(java.lang.String gender)
	{
		setgender(getContext(), gender);
	}

	/**
	 * Set value of gender
	 * @param context
	 * @param gender
	 */
	public final void setgender(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String gender)
	{
		getMendixObject().setValue(context, MemberNames.gender.toString(), gender);
	}

	/**
	 * @return the IMendixObject instance of this proxy for use in the Core interface.
	 */
	public final com.mendix.systemwideinterfaces.core.IMendixObject getMendixObject()
	{
		return persoonMendixObject;
	}

	/**
	 * @return the IContext instance of this proxy, or null if no IContext instance was specified at initialization.
	 */
	public final com.mendix.systemwideinterfaces.core.IContext getContext()
	{
		return context;
	}

	@java.lang.Override
	public boolean equals(Object obj)
	{
		if (obj == this) {
			return true;
		}
		if (obj != null && getClass().equals(obj.getClass()))
		{
			final myfirstmodule.proxies.persoon that = (myfirstmodule.proxies.persoon) obj;
			return getMendixObject().equals(that.getMendixObject());
		}
		return false;
	}

	@java.lang.Override
	public int hashCode()
	{
		return getMendixObject().hashCode();
	}

	/**
	 * @return String name of this class
	 */
	public static java.lang.String getType()
	{
		return entityName;
	}

	/**
	 * @return String GUID from this object, format: ID_0000000000
	 * @deprecated Use getMendixObject().getId().toLong() to get a unique identifier for this object.
	 */
	@java.lang.Deprecated
	public java.lang.String getGUID()
	{
		return "ID_" + getMendixObject().getId().toLong();
	}
}
